# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_main_wIndow(object):
    def setupUi(self, main_wIndow):
        main_wIndow.setObjectName("main_wIndow")
        main_wIndow.resize(528, 468)
        main_wIndow.setStyleSheet("")
        self.gridLayout = QtWidgets.QGridLayout(main_wIndow)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.criar_btt = QtWidgets.QPushButton(main_wIndow)
        self.criar_btt.setMinimumSize(QtCore.QSize(50, 60))
        self.criar_btt.setObjectName("criar_btt")
        self.verticalLayout.addWidget(self.criar_btt)
        self.manutencao_btt = QtWidgets.QPushButton(main_wIndow)
        self.manutencao_btt.setMinimumSize(QtCore.QSize(0, 60))
        self.manutencao_btt.setObjectName("manutencao_btt")
        self.verticalLayout.addWidget(self.manutencao_btt)
        self.log_btt = QtWidgets.QPushButton(main_wIndow)
        self.log_btt.setMinimumSize(QtCore.QSize(0, 60))
        self.log_btt.setObjectName("log_btt")
        self.verticalLayout.addWidget(self.log_btt)
        self.gridLayout.addLayout(self.verticalLayout, 1, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 2, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem1, 0, 0, 1, 1)

        self.retranslateUi(main_wIndow)
        QtCore.QMetaObject.connectSlotsByName(main_wIndow)
        main_wIndow.setTabOrder(self.criar_btt, self.manutencao_btt)
        main_wIndow.setTabOrder(self.manutencao_btt, self.log_btt)

    def retranslateUi(self, main_wIndow):
        _translate = QtCore.QCoreApplication.translate
        main_wIndow.setWindowTitle(_translate("main_wIndow", "Form"))
        self.criar_btt.setText(_translate("main_wIndow", "CRIAR"))
        self.manutencao_btt.setText(_translate("main_wIndow", "MANUTENCAO"))
        self.log_btt.setText(_translate("main_wIndow", "LOG"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    main_wIndow = QtWidgets.QWidget()
    ui = Ui_main_wIndow()
    ui.setupUi(main_wIndow)
    main_wIndow.show()
    sys.exit(app.exec_())
