# -*- coding: utf-8 -*-

# tela_editar implementation generated from reading ui file 'tela_editar_2.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_tela_editar(object):
    def setupUi(self, tela_editar):
        tela_editar.setObjectName("tela_editar")
        tela_editar.resize(659, 520)
        self.verticalLayout = QtWidgets.QVBoxLayout(tela_editar)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(-1, -1, -1, 30)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pesquisa_cbbox = QtWidgets.QComboBox(tela_editar)
        self.pesquisa_cbbox.setObjectName("pesquisa_cbbox")
        self.pesquisa_cbbox.addItem("")
        self.pesquisa_cbbox.addItem("")
        self.horizontalLayout.addWidget(self.pesquisa_cbbox)
        self.textopesquisa_lnedit = QtWidgets.QLineEdit(tela_editar)
        self.textopesquisa_lnedit.setObjectName("textopesquisa_lnedit")
        self.horizontalLayout.addWidget(self.textopesquisa_lnedit)
        self.pesquisar_btt = QtWidgets.QPushButton(tela_editar)
        self.pesquisar_btt.setObjectName("pesquisar_btt")
        self.horizontalLayout.addWidget(self.pesquisar_btt)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.tabela = QtWidgets.QTreeWidget(tela_editar)
        self.tabela.setObjectName("tabela")
        self.verticalLayout.addWidget(self.tabela)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setContentsMargins(-1, -1, -1, 20)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.editar_btt = QtWidgets.QPushButton(tela_editar)
        self.editar_btt.setObjectName("editar_btt")
        self.horizontalLayout_2.addWidget(self.editar_btt)
        self.inativar_btt = QtWidgets.QPushButton(tela_editar)
        self.inativar_btt.setObjectName("inativar_btt")
        self.horizontalLayout_2.addWidget(self.inativar_btt)
        self.excluir_btt = QtWidgets.QPushButton(tela_editar)
        self.excluir_btt.setStyleSheet("background-color: rgb(255, 66, 66);")
        self.excluir_btt.setObjectName("excluir_btt")
        self.horizontalLayout_2.addWidget(self.excluir_btt)
        self.fechar_btt = QtWidgets.QPushButton(tela_editar)
        self.fechar_btt.setObjectName("fechar_btt")
        self.horizontalLayout_2.addWidget(self.fechar_btt)
        self.verticalLayout.addLayout(self.horizontalLayout_2)

        self.retranslateUi(tela_editar)
        QtCore.QMetaObject.connectSlotsByName(tela_editar)
        tela_editar.setTabOrder(self.pesquisa_cbbox, self.textopesquisa_lnedit)
        tela_editar.setTabOrder(self.textopesquisa_lnedit, self.pesquisar_btt)
        tela_editar.setTabOrder(self.pesquisar_btt, self.editar_btt)
        tela_editar.setTabOrder(self.editar_btt, self.excluir_btt)
        tela_editar.setTabOrder(self.excluir_btt, self.fechar_btt)

    def retranslateUi(self, tela_editar):
        _translate = QtCore.QCoreApplication.translate
        tela_editar.setWindowTitle(_translate("tela_editar", "tela_editar"))
        self.pesquisa_cbbox.setItemText(0, _translate("tela_editar", "CODIGO"))
        self.pesquisa_cbbox.setItemText(1, _translate("tela_editar", "NOME"))
        self.pesquisar_btt.setText(_translate("tela_editar", "PESQUISAR"))
        self.tabela.headerItem().setText(0, _translate("tela_editar", "CODIGO"))
        self.tabela.headerItem().setText(1, _translate("tela_editar", "NOME"))
        self.tabela.headerItem().setText(2, _translate("tela_editar", "DATACADASTRO"))
        self.tabela.headerItem().setText(3, _translate("tela_editar", "SITUACAO"))
        self.tabela.headerItem().setText(4, _translate("tela_editar", "DATAINATIVACAO"))
        self.tabela.headerItem().setText(5, _translate("tela_editar", "DTNASC"))
        self.tabela.headerItem().setText(6, _translate("tela_editar", "SETOR"))
        self.editar_btt.setText(_translate("tela_editar", "EDITAR"))
        self.inativar_btt.setText(_translate("tela_editar", "INATIVAR"))
        self.excluir_btt.setText(_translate("tela_editar", "EXCLUIR"))
        self.fechar_btt.setText(_translate("tela_editar", "FECHAR"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    tela_editar = QtWidgets.QWidget()
    ui = Ui_tela_editar()
    ui.setupUi(tela_editar)
    tela_editar.show()
    sys.exit(app.exec_())
